manifest = "b39102d9360a5b8bc177b0fcf18cf983dc155892b7173da67d2e1ec0985e7e2b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "branch=master" ]
revision = "6587b84e4fb0711bd7d0930b415ca7937e72021b"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "fc4d65435c49b5b4fbbf0d4867ee8f69bfd42ef1"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "82480080750b32b3ef2e3f12157b5c556ae35c0d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "94aa5268c1a74468be94b40afd730aea1730ceab"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "3f0711cabd643ed902ff3ae3d6746ba2f7256e4e"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "73def0812b7235e0312079c729342787819bf1d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "branch=master" ]
revision = "dc09aaf60934327c4e2e044097c0d5f6a8151702"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "4b9da4628bc69ad0e9b244d3ec885f2eadac95d8"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "a34caf51f831ffb77d1057c668b5db620863d191"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"
